[versions]
java = "21"
kotlin = "2.3.0"
kotlinx-coroutines = "1.10.2"
kotlinx-serialization = "1.9.0"
kotlinx-datetime = "0.7.1"
ktor = "3.3.3"
slf4j = "2.0.17"
logback-classic = "1.5.25"
arrow = "2.2.1.1"
warden-makoto = "0.9.9999.1"
hoplite = "3.0.0.RC1"
spotless = "8.1.0"
ktlint = "1.8.0"
indispensable = "3.19.1"
supreme = "0.11.1"
jib = "3.5.2"
kover = "0.9.4"
dependency-check = "12.2.0"

[libraries]
kotlin-bom = { module = "org.jetbrains.kotlin:kotlin-bom", version.ref = "kotlin" }
kotlin-stdlib = { module = "org.jetbrains.kotlin:kotlin-stdlib" }
kotlin-test = { module = "org.jetbrains.kotlin:kotlin-test" }
kotlinx-coroutines-bom = { module = "org.jetbrains.kotlinx:kotlinx-coroutines-bom", version.ref = "kotlinx-coroutines" }
kotlinx-coroutines-core = { module = "org.jetbrains.kotlinx:kotlinx-coroutines-core" }
kotlinx-coroutines-test = { module = "org.jetbrains.kotlinx:kotlinx-coroutines-test" }
kotlinx-serialization-bom = { module = "org.jetbrains.kotlinx:kotlinx-serialization-bom", version.ref = "kotlinx-serialization" }
kotlinx-serialization-json = { module = "org.jetbrains.kotlinx:kotlinx-serialization-json" }
kotlinx-datetime = { module = "org.jetbrains.kotlinx:kotlinx-datetime", version.ref = "kotlinx-datetime" }
ktor-bom = { module = "io.ktor:ktor-bom", version.ref = "ktor" }
ktor-server-core = { module = "io.ktor:ktor-server-core" }
ktor-server-cio = { module = "io.ktor:ktor-server-cio" }
ktor-server-content-negotiation = { module = "io.ktor:ktor-server-content-negotiation" }
ktor-serialization-kotlinx-json = { module = "io.ktor:ktor-serialization-kotlinx-json" }
ktor-server-caching-headers = { module = "io.ktor:ktor-server-caching-headers" }
ktor-server-forwarded-header = { module = "io.ktor:ktor-server-forwarded-header" }
ktor-server-swagger = { module = "io.ktor:ktor-server-swagger" }
ktor-server-test-host = { module = "io.ktor:ktor-server-test-host" }
ktor-client-core = { module = "io.ktor:ktor-client-core" }
ktor-client-cio = { module = "io.ktor:ktor-client-cio" }
ktor-client-content-negotiation = { module = "io.ktor:ktor-client-content-negotiation" }
slf4j-bom = { module = "org.slf4j:slf4j-bom", version.ref = "slf4j" }
slf4j-api = { module = "org.slf4j:slf4j-api" }
logback-classic = { module = "ch.qos.logback:logback-classic", version.ref = "logback-classic" }
arrow-bom = { module = "io.arrow-kt:arrow-stack", version.ref = "arrow" }
arrow-core = { module = "io.arrow-kt:arrow-core" }
arrow-core-serialization = { module = "io.arrow-kt:arrow-core-serialization" }
arrow-suspendapp = { module = "io.arrow-kt:suspendapp" }
arrow-suspendapp-ktor = { module = "io.arrow-kt:suspendapp-ktor" }
bouncycastle-bom = { module = "org.bouncycastle:bcbom" }
warden-makoto = { module = "at.asitplus.warden:makoto", version.ref = "warden-makoto" }
hoplite-bom = { module = "com.sksamuel.hoplite:hoplite-bom" }
hoplite-core = { module = "com.sksamuel.hoplite:hoplite-core", version.ref = "hoplite" }
indispensable-bom = { module = "at.asitplus.signum:indispensable-bom" }
indispensable-josef = { module = "at.asitplus.signum:indispensable-josef", version.ref = "indispensable" }
supreme = { module = "at.asitplus.signum:supreme", version.ref = "supreme" }

[plugins]
kotlin-jvm = { id = "org.jetbrains.kotlin.jvm", version.ref = "kotlin" }
kotlin-plugin-serialization = { id = "org.jetbrains.kotlin.plugin.serialization", version.ref = "kotlin" }
spotless = { id = "com.diffplug.spotless", version.ref = "spotless" }
jib = { id = "com.google.cloud.tools.jib", version.ref = "jib" }
kover = { id = "org.jetbrains.kotlinx.kover", version.ref = "kover" }
dependency-check = { id = "org.owasp.dependencycheck", version.ref = "dependency-check" }
